-- TrimSlot schema (PostgreSQL 14+; developed against 17). Idempotency of the runner: each file runs once, in a transaction.
-- CONVENTIONS
--   * every instant is timestamptz (stored UTC, always rendered/computed in Africa/Lagos by the app and by the generated columns below)
--   * money is integer kobo
--   * "wall clock" schedule values (opening hours, breaks) are minutes-from-midnight in Lagos time, not instants

CREATE TABLE users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role          TEXT NOT NULL CHECK (role IN ('customer','barber')),
  name          TEXT NOT NULL,
  email         TEXT UNIQUE,
  phone         TEXT UNIQUE,
  password_hash TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT users_has_contact CHECK (email IS NOT NULL OR phone IS NOT NULL)
);

CREATE TABLE barbers (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id             INTEGER NOT NULL UNIQUE REFERENCES users(id),
  shop_name           TEXT NOT NULL,
  photo_url           TEXT,
  location            TEXT,
  about               TEXT,
  paystack_subaccount TEXT,                       -- ACCT_xxxxxxxx
  verified            BOOLEAN NOT NULL DEFAULT FALSE,   -- set by: npm run admin -- verify-barber <email>
  verified_at         TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_barbers_verified ON barbers (verified);

CREATE TABLE barber_schedule (
  barber_id       INTEGER NOT NULL REFERENCES barbers(id),
  weekday         SMALLINT NOT NULL CHECK (weekday BETWEEN 0 AND 6),   -- 0=Sunday
  is_working      BOOLEAN NOT NULL DEFAULT FALSE,
  start_min       INTEGER NOT NULL DEFAULT 540,
  end_min         INTEGER NOT NULL DEFAULT 1080,
  break_start_min INTEGER,
  break_end_min   INTEGER,
  PRIMARY KEY (barber_id, weekday)
);

CREATE TABLE days_off (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barber_id INTEGER NOT NULL REFERENCES barbers(id),
  date      DATE NOT NULL,
  reason    TEXT,
  UNIQUE (barber_id, date)
);

CREATE TABLE services (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barber_id    INTEGER NOT NULL REFERENCES barbers(id),
  name         TEXT NOT NULL,
  price_kobo   INTEGER NOT NULL CHECK (price_kobo >= 0),
  duration_min INTEGER NOT NULL CHECK (duration_min > 0),
  active       BOOLEAN NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_services_barber ON services (barber_id) WHERE active;

CREATE TABLE bookings (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id       INTEGER NOT NULL REFERENCES users(id),
  barber_id         INTEGER NOT NULL REFERENCES barbers(id),
  service_id        INTEGER NOT NULL REFERENCES services(id),
  family_member_id  INTEGER,                                 -- future: family accounts (nullable, unused in MVP)
  entitlement_type  TEXT NOT NULL DEFAULT 'NONE',            -- future: NONE | SUBSCRIPTION | PAID_TURN ...

  -- The appointment as instants. scheduled_at is NEVER rewritten (early arrivals are served early, not re-timed).
  scheduled_at      TIMESTAMPTZ NOT NULL,
  ends_at           TIMESTAMPTZ NOT NULL,
  -- Lagos-local calendar date / minutes-of-day are DERIVED from the instants, so they can never disagree with them.
  date              DATE     GENERATED ALWAYS AS ((scheduled_at AT TIME ZONE 'Africa/Lagos')::date) STORED,
  start_min         INTEGER  GENERATED ALWAYS AS ((extract(hour   FROM scheduled_at AT TIME ZONE 'Africa/Lagos') * 60
                                                 +  extract(minute FROM scheduled_at AT TIME ZONE 'Africa/Lagos'))::int) STORED,
  end_min           INTEGER  GENERATED ALWAYS AS ((extract(hour   FROM scheduled_at AT TIME ZONE 'Africa/Lagos') * 60
                                                 +  extract(minute FROM scheduled_at AT TIME ZONE 'Africa/Lagos'))::int + duration_min) STORED,

  -- snapshots: later service edits never affect an existing booking
  service_name      TEXT NOT NULL,
  price_kobo        INTEGER NOT NULL CHECK (price_kobo >= 0),
  duration_min      INTEGER NOT NULL CHECK (duration_min > 0),

  status            TEXT NOT NULL CHECK (status IN ('PENDING_PAYMENT','CONFIRMED','ARRIVED','IN_SERVICE','COMPLETED','CANCELLED','NO_SHOW','NOT_SERVED')),
  payment_option    TEXT NOT NULL CHECK (payment_option IN ('ONLINE','ON_ARRIVAL')),
  payment_status    TEXT NOT NULL CHECK (payment_status IN ('PENDING','PAYMENT_DUE','PAID','CREDIT_PENDING','VOID')),
  paid_via          TEXT,                                    -- PAYSTACK | CASH | TRANSFER
  paid_at           TIMESTAMPTZ,
  hold_expires_at   TIMESTAMPTZ,                             -- PENDING_PAYMENT slot hold (also enforced lazily on every read/booking)
  arrival_time      TIMESTAMPTZ,
  arrival_source    TEXT,                                    -- CUSTOMER | BARBER
  service_start     TIMESTAMPTZ,
  service_complete  TIMESTAMPTZ,
  cancelled_at      TIMESTAMPTZ,
  cancelled_by      TEXT,
  barber_hold       BOOLEAN NOT NULL DEFAULT FALSE,          -- barber tapped "Wait"
  skipped_at        TIMESTAMPTZ,                             -- barber tapped "Skip" (back of the queue)
  last_queue_pos    INTEGER,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT bookings_time_order CHECK (ends_at > scheduled_at)
);
CREATE INDEX idx_bookings_barber_date   ON bookings (barber_id, date);
CREATE INDEX idx_bookings_customer_date ON bookings (customer_id, date);
CREATE INDEX idx_bookings_pending_holds ON bookings (hold_expires_at) WHERE status = 'PENDING_PAYMENT';

-- DB-level guard #1: two live bookings can never START at the same instant for one barber.
CREATE UNIQUE INDEX uq_bookings_active_slot ON bookings (barber_id, scheduled_at)
  WHERE status IN ('PENDING_PAYMENT','CONFIRMED','ARRIVED','IN_SERVICE','COMPLETED');
-- DB-level guard #2: a barber can only be serving one customer at a time.
CREATE UNIQUE INDEX uq_bookings_one_in_service ON bookings (barber_id) WHERE status = 'IN_SERVICE';
-- (guard #3, the no-OVERLAP exclusion constraint, lives in 002 because it needs the btree_gist extension)

CREATE TABLE payments (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id        INTEGER NOT NULL REFERENCES bookings(id),
  reference         TEXT NOT NULL UNIQUE,                    -- TS-BOOKING-<id>-<random>; unique => a reference can only ever exist once
  provider          TEXT NOT NULL,                           -- PAYSTACK | MOCK
  amount_kobo       INTEGER NOT NULL,
  fee_kobo          INTEGER NOT NULL DEFAULT 0,
  subaccount        TEXT,
  status            TEXT NOT NULL DEFAULT 'INITIATED' CHECK (status IN ('INITIATED','SUCCESS','FAILED')),
  mock_paid         BOOLEAN NOT NULL DEFAULT FALSE,          -- MOCK mode (non-production) only
  authorization_url TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  verified_at       TIMESTAMPTZ
);
CREATE INDEX idx_payments_booking ON payments (booking_id);

-- Every webhook/callback delivery is recorded. event_key = sha256(raw body + signature validity) so an exact replay
-- of the same event increments delivery_count instead of creating a new row (idempotent storage).
CREATE TABLE payment_events (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source           TEXT NOT NULL CHECK (source IN ('WEBHOOK','CALLBACK')),
  event_key        TEXT NOT NULL UNIQUE,
  event_type       TEXT,
  reference        TEXT,
  signature_valid  BOOLEAN,
  payload          TEXT NOT NULL,                            -- raw body (truncated for unsigned/invalid requests)
  result           TEXT,                                     -- result of the FIRST delivery: processed | already_processed | not_paid | rejected_bad_signature ...
  last_result      TEXT,                                     -- result of the most recent delivery
  delivery_count   INTEGER NOT NULL DEFAULT 1,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_received_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_payment_events_reference ON payment_events (reference);
-- A reference can be *processed* by a webhook at most once, enforced by the database itself.
CREATE UNIQUE INDEX uq_payment_events_processed_ref ON payment_events (reference)
  WHERE source = 'WEBHOOK' AND result = 'processed';

CREATE TABLE audit_log (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id    INTEGER REFERENCES bookings(id),
  actor_user_id INTEGER,
  actor_role    TEXT NOT NULL,                               -- customer | barber | system
  action        TEXT NOT NULL,
  details       JSONB,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_booking ON audit_log (booking_id, id);

CREATE TABLE notifications (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id),
  type       TEXT NOT NULL,
  title      TEXT NOT NULL,
  body       TEXT NOT NULL,
  booking_id INTEGER,
  is_read    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_notif_user ON notifications (user_id, is_read, id DESC);

-- Shared, DB-backed fixed-window rate limiter (works across serverless instances). Old windows are purged by the cron sweeper.
CREATE TABLE rate_limits (
  key          TEXT NOT NULL,
  window_start TIMESTAMPTZ NOT NULL,
  hits         INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (key, window_start)
);
CREATE INDEX idx_rate_limits_window ON rate_limits (window_start);
