-- Shop photos are stored in Postgres (Vercel has no persistent disk and Supabase Storage needs a service-role key we don't hold).
-- One small (<= 300 KB, client-compressed JPEG) image per barber, served through GET /api/barbers/:id/photo with long-lived caching.
CREATE TABLE barber_photos (
  barber_id  INTEGER PRIMARY KEY REFERENCES barbers(id) ON DELETE CASCADE,
  mime       TEXT NOT NULL CHECK (mime IN ('image/jpeg','image/png','image/webp')),
  data       BYTEA NOT NULL CHECK (octet_length(data) BETWEEN 1 AND 307200),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Public "Availability updated" notes shown on the barber page after a barber edits weekly hours (days off are read live from days_off).
CREATE TABLE availability_changes (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barber_id  INTEGER NOT NULL REFERENCES barbers(id) ON DELETE CASCADE,
  kind       TEXT NOT NULL,
  note       TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_availability_changes_barber ON availability_changes (barber_id, id DESC);

-- Same posture as every other table: RLS on, no policies (the app connects with a BYPASSRLS role; PostgREST/anon gets nothing).
ALTER TABLE barber_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE availability_changes ENABLE ROW LEVEL SECURITY;
