-- Subscriptions (barber plans / session packs) and same-barber session credits.

-- Platform-wide rules, ONE row (id = 1). Edited only through the admin CLI / admin API. Barbers can never go outside these limits.
CREATE TABLE platform_settings (
  id                           SMALLINT PRIMARY KEY CHECK (id = 1),
  min_plan_price_kobo          INTEGER NOT NULL DEFAULT 100000    CHECK (min_plan_price_kobo >= 0),       -- NGN 1,000
  max_plan_price_kobo          INTEGER NOT NULL DEFAULT 50000000  CHECK (max_plan_price_kobo >= 0),       -- NGN 500,000
  max_plan_validity_days       INTEGER NOT NULL DEFAULT 90        CHECK (max_plan_validity_days BETWEEN 1 AND 730),
  max_plan_sessions            INTEGER NOT NULL DEFAULT 30        CHECK (max_plan_sessions BETWEEN 1 AND 500),
  platform_fee_percent         NUMERIC(5,2) NOT NULL DEFAULT 0    CHECK (platform_fee_percent BETWEEN 0 AND 100),
  platform_fee_kobo            INTEGER NOT NULL DEFAULT 0         CHECK (platform_fee_kobo >= 0),         -- flat part; 0/0 => falls back to PLATFORM_FEE_* env vars
  credit_expiry_days           INTEGER NOT NULL DEFAULT 30        CHECK (credit_expiry_days BETWEEN 1 AND 365),
  -- refund rules. Credits are never cashable and nothing is ever auto-refunded to a card.
  credit_on_missed_session     BOOLEAN NOT NULL DEFAULT TRUE,     -- no-show / late cancel of a paid session => 1 credit with the same barber
  credit_on_early_cancel_prepaid BOOLEAN NOT NULL DEFAULT FALSE,  -- in-time cancel of a prepaid (online) booking => credit (default: stays CREDIT_PENDING for manual follow-up, as before)
  plan_refund_policy           TEXT NOT NULL DEFAULT 'NONE' CHECK (plan_refund_policy IN ('NONE','MANUAL')), -- unused sessions: no refund / case-by-case (shown to buyers)
  updated_at                   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT plan_price_range CHECK (min_plan_price_kobo <= max_plan_price_kobo)
);
INSERT INTO platform_settings (id) VALUES (1);

CREATE TABLE plans (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barber_id     INTEGER NOT NULL REFERENCES barbers(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  price_kobo    INTEGER NOT NULL CHECK (price_kobo > 0),
  sessions      INTEGER NOT NULL CHECK (sessions > 0),
  validity_days INTEGER NOT NULL CHECK (validity_days > 0),
  active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_plans_barber ON plans (barber_id) WHERE active;

CREATE TABLE plan_services (
  plan_id    INTEGER NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
  service_id INTEGER NOT NULL REFERENCES services(id),
  PRIMARY KEY (plan_id, service_id)
);

-- One row per purchase. Everything a booking needs is snapshotted, so later plan edits never change what a customer already bought.
-- PENDING = checkout started, not paid: invisible to the barber (same rule as unpaid Pay-now bookings). ACTIVE = paid.
CREATE TABLE plan_purchases (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id        INTEGER NOT NULL REFERENCES plans(id),
  customer_id    INTEGER NOT NULL REFERENCES users(id),
  barber_id      INTEGER NOT NULL REFERENCES barbers(id),
  plan_name      TEXT NOT NULL,
  price_kobo     INTEGER NOT NULL CHECK (price_kobo > 0),
  sessions_total INTEGER NOT NULL CHECK (sessions_total > 0),
  sessions_used  INTEGER NOT NULL DEFAULT 0,
  validity_days  INTEGER NOT NULL,
  service_ids    INTEGER[] NOT NULL,
  status         TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','ACTIVE')),
  paid_at        TIMESTAMPTZ,
  expires_at     TIMESTAMPTZ,                                 -- set on payment: paid_at + validity_days. Sessions die with the plan.
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT sessions_within_total CHECK (sessions_used >= 0 AND sessions_used <= sessions_total)
);
CREATE INDEX idx_purchases_customer ON plan_purchases (customer_id, barber_id) WHERE status = 'ACTIVE';
CREATE INDEX idx_purchases_barber   ON plan_purchases (barber_id) WHERE status = 'ACTIVE';

-- A missed paid session becomes ONE credit with the SAME barber. Never cashable. Expiry is enforced by expires_at checks (lazy).
CREATE TABLE session_credits (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id       INTEGER NOT NULL REFERENCES users(id),
  barber_id         INTEGER NOT NULL REFERENCES barbers(id),
  source_booking_id INTEGER UNIQUE REFERENCES bookings(id),   -- UNIQUE: a missed booking can only ever produce one credit
  reason            TEXT NOT NULL,                            -- NO_SHOW | LATE_CANCEL | EARLY_CANCEL
  value_kobo        INTEGER NOT NULL CHECK (value_kobo >= 0), -- usable for any service of that barber priced up to this
  status            TEXT NOT NULL DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE','USED')),
  expires_at        TIMESTAMPTZ NOT NULL,
  used_booking_id   INTEGER REFERENCES bookings(id),
  used_at           TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_credits_customer ON session_credits (customer_id, barber_id, expires_at) WHERE status = 'AVAILABLE';
CREATE INDEX idx_credits_barber   ON session_credits (barber_id, created_at DESC);

-- Bookings can be paid with a plan session or a credit.
ALTER TABLE bookings ADD COLUMN plan_purchase_id INTEGER REFERENCES plan_purchases(id);
ALTER TABLE bookings ADD COLUMN credit_id        INTEGER REFERENCES session_credits(id);
ALTER TABLE bookings DROP CONSTRAINT bookings_payment_option_check;
ALTER TABLE bookings ADD  CONSTRAINT bookings_payment_option_check CHECK (payment_option IN ('ONLINE','ON_ARRIVAL','PLAN','CREDIT'));
ALTER TABLE bookings DROP CONSTRAINT bookings_payment_status_check;
ALTER TABLE bookings ADD  CONSTRAINT bookings_payment_status_check CHECK (payment_status IN ('PENDING','PAYMENT_DUE','PAID','CREDIT_PENDING','CREDITED','VOID'));

-- Payments can now be for a plan purchase instead of a booking (exactly one of the two).
ALTER TABLE payments ALTER COLUMN booking_id DROP NOT NULL;
ALTER TABLE payments ADD COLUMN plan_purchase_id INTEGER REFERENCES plan_purchases(id);
ALTER TABLE payments ADD CONSTRAINT payments_one_target CHECK ((booking_id IS NULL) <> (plan_purchase_id IS NULL));
CREATE INDEX idx_payments_purchase ON payments (plan_purchase_id) WHERE plan_purchase_id IS NOT NULL;

ALTER TABLE platform_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE plans             ENABLE ROW LEVEL SECURITY;
ALTER TABLE plan_services     ENABLE ROW LEVEL SECURITY;
ALTER TABLE plan_purchases    ENABLE ROW LEVEL SECURITY;
ALTER TABLE session_credits   ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------------------------------------------
-- Incomplete-booking rule, tightened: an UNPAID Pay-now attempt (PENDING_PAYMENT) no longer reserves ANY slot.
-- Only complete bookings (paid online, pay-on-arrival, plan/credit) occupy the calendar, so both DB-level guards
-- drop PENDING_PAYMENT. Payment confirmation re-checks the slot under the barber row lock (see applyVerifiedPayment).
-- ---------------------------------------------------------------------------------------------------------------
DROP INDEX IF EXISTS uq_bookings_active_slot;
CREATE UNIQUE INDEX uq_bookings_active_slot ON bookings (barber_id, scheduled_at)
  WHERE status IN ('CONFIRMED','ARRIVED','IN_SERVICE','COMPLETED');
ALTER TABLE bookings DROP CONSTRAINT IF EXISTS bookings_no_overlap;
DO $$
BEGIN
  BEGIN
    CREATE EXTENSION IF NOT EXISTS btree_gist;
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'btree_gist unavailable (%): skipping bookings_no_overlap exclusion constraint', SQLERRM;
    RETURN;
  END;
  ALTER TABLE bookings
    ADD CONSTRAINT bookings_no_overlap
    EXCLUDE USING gist (barber_id WITH =, tstzrange(scheduled_at, ends_at) WITH &&)
    WHERE (status IN ('CONFIRMED','ARRIVED','IN_SERVICE','COMPLETED'));
END
$$;

-- Money that arrived but cannot be honoured (slot taken meanwhile, duplicate/late payment) is flagged here for refund.
ALTER TABLE payments ADD COLUMN refund_status       TEXT CHECK (refund_status IN ('NEEDS_REFUND','REFUND_REQUESTED'));
ALTER TABLE payments ADD COLUMN refund_reason       TEXT;
ALTER TABLE payments ADD COLUMN refund_requested_at TIMESTAMPTZ;
ALTER TABLE payments ADD COLUMN refund_error        TEXT;
CREATE INDEX idx_payments_refund ON payments (refund_status) WHERE refund_status IS NOT NULL;
