-- 007: admin power tools + off-app commission ledger.

-- Accounts: admin can warn / suspend / ban customers (reason shown to the user).
ALTER TABLE users ADD COLUMN account_status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (account_status IN ('ACTIVE','SUSPENDED','BANNED'));
ALTER TABLE users ADD COLUMN status_reason  TEXT;
ALTER TABLE users ADD COLUMN status_at      TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN warn_count     INTEGER NOT NULL DEFAULT 0;

-- Per-barber controls: pause new bookings, fee override (NULL = use the platform fee).
ALTER TABLE barbers ADD COLUMN booking_paused        BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE barbers ADD COLUMN pause_reason          TEXT;
ALTER TABLE barbers ADD COLUMN fee_percent_override  NUMERIC(5,2) CHECK (fee_percent_override IS NULL OR fee_percent_override BETWEEN 0 AND 100);
ALTER TABLE barbers ADD COLUMN fee_flat_kobo_override INTEGER CHECK (fee_flat_kobo_override IS NULL OR fee_flat_kobo_override >= 0);

-- Global controls + commission rules (single settings row).
ALTER TABLE platform_settings ADD COLUMN maintenance_mode        BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE platform_settings ADD COLUMN maintenance_message     TEXT NOT NULL DEFAULT 'Bookings are paused for a short maintenance. Please try again soon.';
ALTER TABLE platform_settings ADD COLUMN feature_plans           BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE platform_settings ADD COLUMN feature_credits         BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE platform_settings ADD COLUMN feature_pay_on_arrival  BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE platform_settings ADD COLUMN commission_enabled      BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE platform_settings ADD COLUMN commission_factor       NUMERIC(5,3) NOT NULL DEFAULT 0.5 CHECK (commission_factor BETWEEN 0 AND 1);   -- off-app commission = factor x the in-app platform fee for the same price
ALTER TABLE platform_settings ADD COLUMN min_barber_payout_percent INTEGER NOT NULL DEFAULT 50 CHECK (min_barber_payout_percent BETWEEN 0 AND 100); -- debt netting never takes the barber below this share of a transaction
ALTER TABLE platform_settings ADD COLUMN ledger_max_debt_kobo    INTEGER NOT NULL DEFAULT 0 CHECK (ledger_max_debt_kobo >= 0);   -- 0 = no limit
ALTER TABLE platform_settings ADD COLUMN ledger_max_age_days     INTEGER NOT NULL DEFAULT 0 CHECK (ledger_max_age_days >= 0);    -- 0 = no limit

-- Money / disputes / ownership of a payment.
ALTER TABLE payments ADD COLUMN barber_id         INTEGER REFERENCES barbers(id);
UPDATE payments p SET barber_id = b.barber_id FROM bookings b WHERE b.id = p.booking_id;
UPDATE payments p SET barber_id = pp.barber_id FROM plan_purchases pp WHERE pp.id = p.plan_purchase_id;
ALTER TABLE payments ADD COLUMN debt_netted_kobo  INTEGER NOT NULL DEFAULT 0 CHECK (debt_netted_kobo >= 0);   -- extra platform share taken at checkout to settle commission debt
ALTER TABLE payments ADD COLUMN disputed          BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE payments ADD COLUMN dispute_note      TEXT;
ALTER TABLE payments ADD COLUMN disputed_at       TIMESTAMPTZ;
CREATE INDEX idx_payments_barber ON payments (barber_id);

-- Credits can be revoked by an admin; plan purchases can be cancelled.
ALTER TABLE session_credits DROP CONSTRAINT IF EXISTS session_credits_status_check;
ALTER TABLE session_credits ADD CONSTRAINT session_credits_status_check CHECK (status IN ('AVAILABLE','USED','REVOKED'));
ALTER TABLE plan_purchases DROP CONSTRAINT IF EXISTS plan_purchases_status_check;
ALTER TABLE plan_purchases ADD CONSTRAINT plan_purchases_status_check CHECK (status IN ('PENDING','ACTIVE','CANCELLED'));

-- Off-app commission ledger: what a barber owes the platform for bookings paid outside the app.
CREATE TABLE commission_ledger (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barber_id       INTEGER NOT NULL REFERENCES barbers(id),
  booking_id      INTEGER REFERENCES bookings(id),
  kind            TEXT NOT NULL DEFAULT 'COMMISSION' CHECK (kind IN ('COMMISSION','ADJUSTMENT')),
  amount_kobo     INTEGER NOT NULL CHECK (amount_kobo > 0),
  remaining_kobo  INTEGER NOT NULL CHECK (remaining_kobo >= 0 AND remaining_kobo <= amount_kobo),
  status          TEXT NOT NULL DEFAULT 'ACCRUED' CHECK (status IN ('ACCRUED','SETTLED','WAIVED')),
  note            TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  settled_at      TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_ledger_booking ON commission_ledger (booking_id) WHERE booking_id IS NOT NULL;   -- a booking accrues at most once (idempotent)
CREATE INDEX idx_ledger_barber_open ON commission_ledger (barber_id, id) WHERE status = 'ACCRUED';

CREATE TABLE ledger_applications (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ledger_id   INTEGER NOT NULL REFERENCES commission_ledger(id),
  payment_id  INTEGER REFERENCES payments(id),
  kind        TEXT NOT NULL CHECK (kind IN ('NETTED','NETTED_REVERSED','MANUAL_SETTLE','WAIVE')),
  amount_kobo INTEGER NOT NULL CHECK (amount_kobo > 0),
  reason      TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_ledger_app_payment ON ledger_applications (payment_id);

-- Broadcasts sent by admins (history) and the complaint / report inbox.
CREATE TABLE broadcasts (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  audience    TEXT NOT NULL CHECK (audience IN ('CUSTOMERS','BARBERS','USER')),
  user_id     INTEGER REFERENCES users(id),
  title       TEXT NOT NULL,
  body        TEXT NOT NULL,
  recipients  INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE reports (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id     INTEGER NOT NULL REFERENCES users(id),
  target_user_id  INTEGER REFERENCES users(id),
  booking_id      INTEGER REFERENCES bookings(id),
  category        TEXT NOT NULL CHECK (category IN ('NO_SHOW','BEHAVIOUR','PAYMENT','QUALITY','SAFETY','OTHER')),
  message         TEXT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','RESOLVED','DISMISSED')),
  admin_note      TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at     TIMESTAMPTZ
);
CREATE INDEX idx_reports_status ON reports (status, id DESC);

ALTER TABLE commission_ledger   ENABLE ROW LEVEL SECURITY;
ALTER TABLE ledger_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE broadcasts          ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports             ENABLE ROW LEVEL SECURITY;
