-- 008: web push, smart customer/barber features (all behind admin toggles), and admin list performance indexes.

/* ---------- web push ---------- */
CREATE TABLE push_subscriptions (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  endpoint     TEXT NOT NULL UNIQUE,
  p256dh       TEXT NOT NULL,
  auth         TEXT NOT NULL,
  user_agent   TEXT,
  failures     INTEGER NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_ok_at   TIMESTAMPTZ
);
CREATE INDEX idx_push_user ON push_subscriptions (user_id);
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;

-- Every notification is pushed exactly once: NULL = not pushed yet. Rows that already exist are marked done so nobody gets old news.
ALTER TABLE notifications ADD COLUMN pushed_at TIMESTAMPTZ;
UPDATE notifications SET pushed_at = now();
CREATE INDEX idx_notif_unpushed ON notifications (id) WHERE pushed_at IS NULL;

/* ---------- smart features ---------- */
ALTER TABLE bookings ADD COLUMN note_to_barber TEXT;
ALTER TABLE bookings ADD COLUMN rem2h_at  TIMESTAMPTZ;
ALTER TABLE bookings ADD COLUMN rem30_at  TIMESTAMPTZ;
ALTER TABLE bookings ADD COLUMN leave_at  TIMESTAMPTZ;
ALTER TABLE barbers  ADD COLUMN delay_min  INTEGER NOT NULL DEFAULT 0 CHECK (delay_min BETWEEN 0 AND 240);
ALTER TABLE barbers  ADD COLUMN delay_date DATE;

CREATE TABLE favourites (
  customer_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  barber_id   INTEGER NOT NULL REFERENCES barbers(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (customer_id, barber_id)
);
CREATE INDEX idx_favourites_barber ON favourites (barber_id);

CREATE TABLE waitlist (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES users(id),
  barber_id   INTEGER NOT NULL REFERENCES barbers(id),
  service_id  INTEGER NOT NULL REFERENCES services(id),
  date        DATE NOT NULL,
  status      TEXT NOT NULL DEFAULT 'WAITING' CHECK (status IN ('WAITING','NOTIFIED','BOOKED','CANCELLED','EXPIRED')),
  notified_at TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_waitlist_active ON waitlist (customer_id, barber_id, date) WHERE status IN ('WAITING','NOTIFIED');
CREATE INDEX idx_waitlist_barber_date ON waitlist (barber_id, date) WHERE status IN ('WAITING','NOTIFIED');

CREATE TABLE reviews (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id  INTEGER NOT NULL UNIQUE REFERENCES bookings(id),
  customer_id INTEGER NOT NULL REFERENCES users(id),
  barber_id   INTEGER NOT NULL REFERENCES barbers(id),
  rating      SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment     TEXT CHECK (comment IS NULL OR length(comment) <= 500),
  reply       TEXT CHECK (reply IS NULL OR length(reply) <= 500),
  replied_at  TIMESTAMPTZ,
  hidden      BOOLEAN NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_reviews_barber ON reviews (barber_id, id DESC) WHERE NOT hidden;
CREATE INDEX idx_reviews_customer ON reviews (customer_id);

CREATE TABLE barber_customer_notes (
  barber_id   INTEGER NOT NULL REFERENCES barbers(id) ON DELETE CASCADE,
  customer_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  note        TEXT NOT NULL CHECK (length(note) <= 1000),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (barber_id, customer_id)
);
ALTER TABLE favourites ENABLE ROW LEVEL SECURITY;
ALTER TABLE waitlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE barber_customer_notes ENABLE ROW LEVEL SECURITY;

/* ---------- admin feature toggles (all default ON except where noted) ---------- */
ALTER TABLE platform_settings ADD COLUMN feature_push          BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE platform_settings ADD COLUMN feature_favourites    BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE platform_settings ADD COLUMN feature_rebook        BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE platform_settings ADD COLUMN feature_reminders     BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE platform_settings ADD COLUMN feature_waitlist      BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE platform_settings ADD COLUMN feature_reviews       BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE platform_settings ADD COLUMN feature_barber_notes  BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE platform_settings ADD COLUMN feature_quick_actions BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE platform_settings ADD COLUMN feature_reliability   BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE platform_settings ADD COLUMN feature_daily_summary BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE platform_settings ADD COLUMN feature_booking_note  BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE platform_settings ADD COLUMN feature_loyalty       BOOLEAN NOT NULL DEFAULT FALSE;   -- costs money: opt-in
ALTER TABLE platform_settings ADD COLUMN loyalty_every_n       INTEGER NOT NULL DEFAULT 10 CHECK (loyalty_every_n BETWEEN 2 AND 100);
ALTER TABLE platform_settings ADD COLUMN loyalty_credit_kobo   INTEGER NOT NULL DEFAULT 100000 CHECK (loyalty_credit_kobo BETWEEN 0 AND 100000000);

/* ---------- admin list performance (keyset pagination + filters + search) ---------- */
-- Fuzzy search indexes need pg_trgm; if the role cannot create it the migration still succeeds (search falls back to a sequential scan).
DO $$
BEGIN
  BEGIN
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
    CREATE INDEX idx_users_name_trgm   ON users USING gin (lower(name) gin_trgm_ops);
    CREATE INDEX idx_users_email_trgm  ON users USING gin (lower(email) gin_trgm_ops);
    CREATE INDEX idx_users_phone_trgm  ON users USING gin (phone gin_trgm_ops);
    CREATE INDEX idx_barbers_shop_trgm ON barbers USING gin (lower(shop_name) gin_trgm_ops);
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'pg_trgm search indexes skipped: %', SQLERRM;
  END;
END $$;
CREATE INDEX idx_users_role_id        ON users (role, id DESC);
CREATE INDEX idx_users_status         ON users (account_status, id DESC) WHERE account_status <> 'ACTIVE';
CREATE INDEX idx_bookings_status_date ON bookings (status, date DESC, id DESC);
CREATE INDEX idx_bookings_date        ON bookings (date DESC, id DESC);
CREATE INDEX idx_bookings_customer_status ON bookings (customer_id, status);
CREATE INDEX idx_bookings_reminders   ON bookings (scheduled_at) WHERE status IN ('CONFIRMED','ARRIVED');
CREATE INDEX idx_payments_status      ON payments (status, id DESC);
CREATE INDEX idx_audit_action         ON audit_log (action, id DESC);
CREATE INDEX idx_notif_user_id        ON notifications (user_id, id DESC);
CREATE INDEX idx_credits_status       ON session_credits (status, id DESC);
CREATE INDEX idx_purchases_status     ON plan_purchases (status, id DESC);
CREATE INDEX idx_audit_actor          ON audit_log (actor_role, id DESC);
CREATE INDEX idx_payments_verified    ON payments (verified_at) WHERE status = 'SUCCESS';
CREATE INDEX idx_bookings_credit_pending ON bookings (id) WHERE payment_status = 'CREDIT_PENDING';
CREATE INDEX idx_bookings_barber_status ON bookings (barber_id, status, date DESC);
CREATE INDEX idx_ledger_created       ON commission_ledger (created_at) WHERE status = 'ACCRUED';
CREATE INDEX idx_waitlist_status      ON waitlist (status, id DESC);
