-- 011: refund-vs-credit rules (refund starts pending admin approval, auto-approves after N hours), admin alerts + preferences,
--      editable published numbers, terms/privacy acceptance log, account deletion/anonymisation, retention settings, customer avatars.
-- Nothing here rewrites existing rows. Legacy CREDIT_PENDING bookings stay valid and are still resolved from "Refund decisions".

/* ---------- refunds: PENDING_APPROVAL -> (admin approves | auto-approves after N hours) -> NEEDS_REFUND -> REFUND_REQUESTED, or REJECTED ---------- */
ALTER TABLE payments DROP CONSTRAINT IF EXISTS payments_refund_status_check;
ALTER TABLE payments ADD CONSTRAINT payments_refund_status_check
  CHECK (refund_status IN ('PENDING_APPROVAL','NEEDS_REFUND','REFUND_REQUESTED','REFUNDED','REJECTED'));
ALTER TABLE payments ADD COLUMN refund_due_at     TIMESTAMPTZ;   -- when a PENDING_APPROVAL refund auto-approves
ALTER TABLE payments ADD COLUMN refund_decided_at TIMESTAMPTZ;
ALTER TABLE payments ADD COLUMN refund_decided_by TEXT CHECK (refund_decided_by IN ('admin','auto'));
CREATE INDEX idx_payments_refund_due ON payments (refund_due_at) WHERE refund_status = 'PENDING_APPROVAL';

ALTER TABLE bookings DROP CONSTRAINT IF EXISTS bookings_payment_status_check;
ALTER TABLE bookings ADD CONSTRAINT bookings_payment_status_check
  CHECK (payment_status IN ('PENDING','PAYMENT_DUE','PAID','CREDIT_PENDING','CREDITED','VOID','REFUND_PENDING','REFUNDED','REFUND_DECLINED'));

/* ---------- admin-editable published numbers + retention + document versions ---------- */
ALTER TABLE platform_settings ADD COLUMN cancel_cutoff_min           INTEGER NOT NULL DEFAULT 30  CHECK (cancel_cutoff_min BETWEEN 0 AND 1440);
ALTER TABLE platform_settings ADD COLUMN payment_hold_min            INTEGER NOT NULL DEFAULT 15  CHECK (payment_hold_min BETWEEN 1 AND 180);
ALTER TABLE platform_settings ADD COLUMN refund_auto_approve_hours   INTEGER NOT NULL DEFAULT 3   CHECK (refund_auto_approve_hours BETWEEN 0 AND 168);
ALTER TABLE platform_settings ADD COLUMN liability_cap_kobo          BIGINT  NOT NULL DEFAULT 0   CHECK (liability_cap_kobo >= 0);   -- 0 = "not set yet" (the Terms show a placeholder)
ALTER TABLE platform_settings ADD COLUMN retention_events_days       INTEGER NOT NULL DEFAULT 400 CHECK (retention_events_days BETWEEN 30 AND 3650);   -- raw Paystack webhook/callback payloads
ALTER TABLE platform_settings ADD COLUMN retention_bad_events_days   INTEGER NOT NULL DEFAULT 30  CHECK (retention_bad_events_days BETWEEN 1 AND 3650); -- payloads with an invalid signature
ALTER TABLE platform_settings ADD COLUMN retention_notifications_days INTEGER NOT NULL DEFAULT 180 CHECK (retention_notifications_days BETWEEN 7 AND 3650);
ALTER TABLE platform_settings ADD COLUMN retention_push_stale_days   INTEGER NOT NULL DEFAULT 60  CHECK (retention_push_stale_days BETWEEN 7 AND 3650);
ALTER TABLE platform_settings ADD COLUMN retention_deleted_days      INTEGER NOT NULL DEFAULT 30  CHECK (retention_deleted_days BETWEEN 1 AND 3650);   -- soft-deleted records are erased/anonymised after this
ALTER TABLE platform_settings ADD COLUMN retention_checkout_days     INTEGER NOT NULL DEFAULT 2   CHECK (retention_checkout_days BETWEEN 1 AND 365);  -- never-paid plan checkouts
ALTER TABLE platform_settings ADD COLUMN retention_rate_limit_hours  INTEGER NOT NULL DEFAULT 2   CHECK (retention_rate_limit_hours BETWEEN 1 AND 720);
ALTER TABLE platform_settings ADD COLUMN retention_admin_alerts_days INTEGER NOT NULL DEFAULT 90  CHECK (retention_admin_alerts_days BETWEEN 7 AND 3650);
ALTER TABLE platform_settings ADD COLUMN retention_last_run_at       TIMESTAMPTZ;
ALTER TABLE platform_settings ADD COLUMN terms_version               TEXT NOT NULL DEFAULT '1' CHECK (length(terms_version) BETWEEN 1 AND 30);
ALTER TABLE platform_settings ADD COLUMN privacy_version             TEXT NOT NULL DEFAULT '1' CHECK (length(privacy_version) BETWEEN 1 AND 30);
ALTER TABLE platform_settings ADD COLUMN barber_agreement_version    TEXT NOT NULL DEFAULT '1' CHECK (length(barber_agreement_version) BETWEEN 1 AND 30);

/* ---------- acceptance log (who accepted which document version, when, from where) ---------- */
CREATE TABLE consent_log (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER NOT NULL REFERENCES users(id),
  document    TEXT NOT NULL CHECK (document IN ('terms','privacy','barber_agreement')),
  version     TEXT NOT NULL,
  accepted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source      TEXT NOT NULL DEFAULT 'signup' CHECK (source IN ('signup','reaccept')),
  ip          TEXT,
  user_agent  TEXT
);
CREATE INDEX idx_consent_user ON consent_log (user_id, document, id DESC);
ALTER TABLE consent_log ENABLE ROW LEVEL SECURITY;

/* ---------- self-service deletion / anonymisation ---------- */
ALTER TABLE users ADD COLUMN anonymised_at          TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN deletion_requested_at  TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN deletion_request_note  TEXT;
CREATE INDEX idx_users_deletion_req ON users (deletion_requested_at) WHERE deletion_requested_at IS NOT NULL AND anonymised_at IS NULL;

/* ---------- customer avatars (same approach as barber_photos: small client-compressed JPEG stored in Postgres) ---------- */
CREATE TABLE user_avatars (
  user_id    INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  mime       TEXT NOT NULL,
  data       BYTEA NOT NULL CHECK (octet_length(data) <= 150000),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE user_avatars ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ADD COLUMN avatar_url TEXT;
ALTER TABLE users ADD COLUMN avatar_removed_at TIMESTAMPTZ;      -- set when an admin removes a photo (moderation)

/* ---------- admin alerts (admin signs in with a key, not a user account, so alerts live in their own tables) ---------- */
CREATE TABLE admin_notifications (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event      TEXT NOT NULL,
  title      TEXT NOT NULL,
  body       TEXT NOT NULL,
  link       TEXT,
  ref_key    TEXT,
  in_app     BOOLEAN NOT NULL DEFAULT TRUE,
  push       BOOLEAN NOT NULL DEFAULT FALSE,
  read_at    TIMESTAMPTZ,
  pushed_at  TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_admin_notif_recent ON admin_notifications (id DESC);
CREATE INDEX idx_admin_notif_unpushed ON admin_notifications (id) WHERE push AND pushed_at IS NULL;
CREATE INDEX idx_admin_notif_ref ON admin_notifications (event, ref_key, created_at DESC);
CREATE TABLE admin_push_subscriptions (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  endpoint   TEXT NOT NULL UNIQUE,
  p256dh     TEXT NOT NULL,
  auth       TEXT NOT NULL,
  user_agent TEXT,
  failures   INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_ok_at TIMESTAMPTZ
);
CREATE TABLE admin_notification_prefs (
  event  TEXT PRIMARY KEY,
  in_app BOOLEAN NOT NULL DEFAULT TRUE,
  push   BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE admin_notification_settings (
  id              SMALLINT PRIMARY KEY CHECK (id = 1),
  quiet_enabled   BOOLEAN NOT NULL DEFAULT FALSE,
  quiet_start_min INTEGER NOT NULL DEFAULT 1320 CHECK (quiet_start_min BETWEEN 0 AND 1439),   -- 22:00 Lagos
  quiet_end_min   INTEGER NOT NULL DEFAULT 420  CHECK (quiet_end_min BETWEEN 0 AND 1439)      -- 07:00 Lagos
);
INSERT INTO admin_notification_settings (id) VALUES (1);
ALTER TABLE admin_notifications         ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_push_subscriptions    ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_notification_prefs    ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_notification_settings ENABLE ROW LEVEL SECURITY;
