-- 014: "Emergency, please help" requests on locked bookings (customer -> barber), with escalation to staff when the barber does not answer.
-- Additive only: one new table. One OPEN request per booking is enforced by a partial unique index.
CREATE TABLE help_requests (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id   INTEGER NOT NULL REFERENCES bookings(id),
  customer_id  INTEGER NOT NULL REFERENCES users(id),
  note         TEXT NOT NULL CHECK (length(note) BETWEEN 1 AND 200),
  status       TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','RELEASED','COME_LATER','CLOSED')),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  answered_at  TIMESTAMPTZ,
  escalated_at TIMESTAMPTZ,     -- set once staff were told because nobody answered in time
  report_id    INTEGER          -- the staff report raised on escalation (plain number, no foreign key: reports can be deleted)
);
CREATE UNIQUE INDEX uq_help_one_open ON help_requests (booking_id) WHERE status = 'OPEN';
CREATE INDEX idx_help_booking ON help_requests (booking_id, id DESC);
CREATE INDEX idx_help_open_due ON help_requests (created_at) WHERE status = 'OPEN' AND escalated_at IS NULL;
ALTER TABLE help_requests ENABLE ROW LEVEL SECURITY;
